In [22]:
import pandas as pd
import numpy as np
df_pt_full = pd.read_csv('/Users/dahailiu/Desktop/DM for Cancer /NLST dataset/participant.data.d100517.csv')
df_lc = pd.read_csv('/Users/dahailiu/Desktop/DM for Cancer /NLST dataset/Lung Cancer/lung_cancer.data.d100517.csv')
print(df_pt_full.shape)
print(df_lc.shape)

(53452, 324)
(2150, 48)

In [27]:
df_pt_full.head(5)

,cen,dataset_version,elig,ineligible,pid,rndgroup,study,age,educat,ethnic,...,progsite_pleura_ever,progsite_pleura_num,progsite_skin_1st,progsite_skin_days,progsite_skin_ever,progsite_skin_num,progsite_unk_1st,progsite_unk_days,progsite_unk_ever,progsite_unk_num
0,BG,2011.02.03/10.05.17,2,NaN,100001,2,1,70,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AF,2011.02.03/10.05.17,2,NaN,100002,1,1,66,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AR,2011.02.03/10.05.17,2,NaN,100003,2,1,64,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AF,2011.02.03/10.05.17,2,NaN,100004,1,1,60,5,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AA,2011.02.03/10.05.17,2,NaN,100005,1,1,64,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df_pt = df_pt_full.loc[df_pt_full['rndgroup'] == 1]
df_pt.shape

(26722, 324)

In [30]:
df_lc.head(5)

,dataset_version,pid,candx_days,clinical_m,clinical_m_7thed,clinical_n,clinical_n_7thed,clinical_stag,clinical_t,clinical_t_7thed,...,path_n_7thed,path_stag,path_t,path_t_7thed,source_best_stage,stage_only,stage_sum,study_yr,topog_source,valcsg
0,2011.02.03/10.05.17,100012,454,2.0,2.0,2.0,2.0,3,4.0,2.0,...,2.0,3,4.0,2.0,1,99,NaN,1,2.0,NaN
1,2011.02.03/10.05.17,100049,2428,2.0,2.0,2.0,2.0,7,6.0,7.0,...,NaN,99,NaN,NaN,2,7,1.0,6,1.0,NaN
2,2011.02.03/10.05.17,100055,148,3.0,3.0,4.0,4.0,10,5.0,5.0,...,NaN,99,NaN,NaN,2,10,3.0,0,NaN,NaN
3,2011.02.03/10.05.17,100147,491,2.0,2.0,2.0,2.0,3,4.0,3.0,...,2.0,3,4.0,3.0,1,3,1.0,1,2.0,NaN
4,2011.02.03/10.05.17,100158,795,2.0,2.0,2.0,2.0,3,4.0,2.0,...,2.0,3,4.0,2.0,1,99,NaN,2,2.0,NaN

In [31]:
df_pt_pd = pd.merge(df_pt, df_lc, how='left', left_on='pid', right_on='pid')
df_pt_pd.shape

(26781, 371)

Size (CT) (Spiral CT Abnormalities, re-read)
Location (CT) (Spiral CT Abnormalities, re-read)
Patient demographics (Participant dataset)
Diagnosis (Pathology) (Participant dataset)

Question for Jinglu:
1. I left joined on patient
2. Look at the shape of the dataset
3. Ask for her R code
4. I used csv instead of sas file, is this fine?
5. Talking about the response variable, there are different stages
6. In df_pt, there are a lot of patient demographic features, which one should I use? (Did you mean only the demographic section of demographic? What about other features, including smoking,....etc)What did you mean by Diagnosis (Pathology) features
7. Can I examine what you did in your R code?